theme: jekyll-theme-slate
![Teach Access Logo](images/teach_access_logo.svg)
title: <a href="https://kristinaengland.github.io/accessibility-skills-hiring-toolkit/">Teach Access Accessibility Skills Hiring Toolkit</a>
